name: Blog Feed to Blogger

on:
  schedule:
    - cron: '0 10,22 * * *'
  workflow_dispatch:

jobs:
  run-blog-feed:
    runs-on: ubuntu-latest

    env:
      BLOG_ID: ${{ secrets.BLOG_ID }}
      IMG_PREFIX: ${{ secrets.IMG_PREFIX }}
      FEED_URL: ${{ secrets.FEED_URL }}
      POSTED_FILE: posted_titles.json
      SERVICE_ACCOUNT_FILE: service_account.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser beautifulsoup4 requests deep-translator google-api-python-client google-auth google-auth-oauthlib

      - name: Create service account file
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Run Blog Feed Script
        run: python blog_feed_to_blogger.py
